### ISSUE TITLE
直播模式

### ISSUE THREAD

**Issue by JiahengHe** [AgoraIO-Usecase/AgoraMeeting-Desktop#1]
web端无法开启视频和语音。

**Comment by QinZhen001** [comment]
你好 请问使用的最新的代码吗

**Comment by JiahengHe** [comment]
嘿，好了。&nbsp; 我刚刚下了最新代码试了一下可以了。非常感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AgoraIO-Usecase/AgoraMeeting-Desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AgoraIO-Usecase/AgoraMeeting-Desktop] 直播模式 (#1)





 
你好 请问使用的最新的代码吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiahengHe** [comment]
你好，请问下在哪里能设置隐藏下面的功能开关呢？
![image](https://user-images.githubusercontent.com/26545462/129534510-6d70b901-e056-4fc1-82d1-3f390af3372f.png)

**Comment by QinZhen001** [comment]
你好 你可以看看最新的代码 和 README  可以修改packages/agora-meeting-sdk/src/ui-kit/capabilities/containers/footer 然后通过run:demo查看效果

**Comment by JiahengHe** [comment]
嗷嗷，好的，谢谢。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AgoraIO-Usecase/AgoraMeeting-Desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AgoraIO-Usecase/AgoraMeeting-Desktop] 直播模式 (#1)





 
你好 你可以看看最新的代码 和 README  可以修改packages/agora-meeting-sdk/src/ui-kit/capabilities/containers/footer 然后通过run:demo查看效果
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiahengHe** [comment]
最新项目更新后，yarn install 后，yarn run run:demo，一直报这个错呢。
![B)_@ WL7X5J 6(G7 VTB4U](https://user-images.githubusercontent.com/26545462/129833113-077d1a5e-8e5d-4fe3-a7ca-ddeab96f24bb.png)

**Comment by QinZhen001** [comment]
你好 你可以删除根项目的node_modules 和 子项目的node_modules 在yarn install试试。如果不行可以试试删除yarn.lock 在yarn install重装一下依赖

**Comment by JiahengHe** [comment]
删除yarn.lock，重装依赖就好了。
